// import './globals.css'
import NavigationBar from "@/comonents/NavigationBar";
import global from "./globals.scss"; 

import { Inter } from 'next/font/google'
import { Toast, Toaster } from "react-hot-toast"; 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavigationBar /> */}
        <Toaster position="top-center" toastOptions={{ duration: 10000 }} />
        {children}
      </body>
    </html>
  );
}
